project:
  type: website

website:
  title: "June Harkrider"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: custom.scss
    css: custom.css
    toc: true

editor: visual

