project:
  type: website
  output-dir: docs

website:
  navbar:
    background: light
    foreground: dark
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - cv.qmd

format:
  html:
    grid: 
      body-width: 800px
    page-layout: full
    theme: custom.scss
    css: custom.css
    toc: true

editor: source

